sudo: true

addons:
  apt:
    packages:
      - oracle-java8-set-default
before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.2.0.deb && sudo dpkg -i --force-confnew elasticsearch-5.2.0.deb && sudo service elasticsearch start

language: php

php:
  - 7.0
  - 7.1

env:
  global:
    - TYPO3_DATABASE_NAME="typo3_ci"
    - TYPO3_DATABASE_HOST="127.0.0.1"
    - TYPO3_DATABASE_USERNAME="travis"
    - TYPO3_DATABASE_PASSWORD=""
    - typo3DatabaseName="typo3_ci"
    - typo3DatabaseHost="127.0.0.1"
    - typo3DatabaseUsername="travis"
    - typo3DatabasePassword=""
  matrix:
    - TYPO3_VERSION="~8"
    - TYPO3_VERSION="dev-master"

matrix:
  fast_finish: true
  exclude:
  allow_failures:
    - env: TYPO3_VERSION="~8"
      php: 7.0
    - env: TYPO3_VERSION="~8"
      php: 7.1
    - env: TYPO3_VERSION="dev-master"
      php: 7.0
    - env: TYPO3_VERSION="dev-master"
      php: 7.1

services:
  - mysql

install: make install

script:
  - make unitTests
  - make functionalTests

after_script:
  - make uploadCodeCoverage
  - make clean

cache:
  directories:
    - $HOME/.composer/cache
